# Generated by Django 3.1.7 on 2023-04-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurate', '0003_auto_20230420_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='parent_school',
            field=models.CharField(choices=[('0', 'SEDS'), ('1', 'SSH'), ('2', 'SMG'), ('3', 'SME'), ('4', 'Graduate')], default=1, max_length=32),
        ),
    ]
